### ISSUE TITLE
Contradicting messaging around approvals

### ISSUE THREAD

**Issue by bmaher** [zalando-incubator/Zincr#17]
In Zincr's messaging around approvals, there are two contradictory statements:

> Not enough people have approved this pull request - please ensure that atleast 2 users who have not contributed to this pull request approve the changes.
> 
> ❌ 1 approvals of 2 required (Including author of this pull request)

In the first sentence, it claims that two people that are not involved in the PR, i.e. excluding the author, are required for approval. However, in the subsequent failure message it shows that the author is included in the count (as is I believe the expected behaviour).

**Comment by perploug** [comment]
Yeah, that should definitely be more clear. thinking it over I've come to structure of explicitely listing approvals why, so the message would be somewhat like this:

At least 3 approvals are required:
- ✅ Approved by PR author bmaher
- ✅ Approved by team member svend
- ❌ 1 additional approval needed
